version: '3.8'

services:
  langflow:
    image: langflowai/langflow:latest
    container_name: langflow-1
    restart: always
    environment:
      - ASTRA_DB_TOKEN=${ASTRA_DB_TOKEN}
      - ASTRA_DB_ENDPOINT=${ASTRA_DB_ENDPOINT}
      - LANGFLOW_MCP_PORT=7860
      - MCP_SERVER_URL=http://localhost:7860/api/v1/mcp/sse
    ports:
      - "7860:7860"
    volumes:
      - ./logs:/app/logs
      - ./src/utils/mcp:/app/src/utils/mcp
    networks:
      - langflow-network

networks:
  langflow-network:
    name: langflow-network