version: '3'

services:
  bolt-diy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - OLLAMA_API_BASE_URL=https://ollamaapi.coolify.lintserver.com/
