version: '3.8'

services:
  langflow:
    container_name: langflow-1
    image: langflowai/langflow:latest
    restart: always
    environment:
      - ASTRA_DB_TOKEN=${ASTRA_DB_TOKEN}
      - ASTRA_DB_ENDPOINT=${ASTRA_DB_ENDPOINT}
      - LANGFLOW_MCP_PORT=7860
      - MCP_SERVER_URL=http://127.0.0.1:7860/api/v1/mcp/sse
      - LANGFLOW_DATABASE_URL=sqlite:///data/langflow.db
    ports:
      - "7860:7860"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./flows:/app/flows
      - .:/app/project
    networks:
      - langflow-network

  bolt-new-any-llm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bolt-new-any-llm
    volumes:
      - .:/app
    depends_on:
      - langflow
    networks:
      - langflow-network

networks:
  langflow-network:
    name: langflow-network