#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"
send_metrics = false
nodejs_compat = true

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
